total_timesteps: 2e7
n_eval_episodes: 100
n_test_episodes: 10
n_envs: 16
n_frames_stack: 4
recurrent: false
name: ppo
model_kwargs:
  initial_learning_rate: 3e-4  # prvi trening: 1e-3, drugi: 3e-4
  final_learning_rate: 3e-6  # prvi trening: 3e-5, drugi: 3e-6
  # batch_size: 256
  # gamma: 0.99
  # horizon: 128
  # n_epochs: 4
  # gae_lambda: 0.95
  # clip_range: 0.2
  # clip_range_vf: 0.5
  # normalize_advantage: True
  # ent_coef: 0.01
  # vf_coef: 0.5
  # max_grad_norm: 0.5
  # use_sde: False
  # sde_sample_freq: 1

  # Sa ovim radi!!!
  # initial_learning_rate: 0.0010056856105812677
  # final_learning_rate: 0.0005388403129100248
  batch_size: 256
  gamma: 0.8108071290665859
  horizon: 1024
  n_epochs: 4  # prvi trening: 6, drugi: 4
  gae_lambda: 0.9452281119742252
  clip_range: 0.1
  clip_range_vf: 0.08341734780140342
  normalize_advantage: true
  ent_coef: 0.045732238989694494
  vf_coef: 0.8177283657817492
  max_grad_norm: 0.5215982006116593
  use_sde: false
  sde_sample_freq: 1